export const productCategories = [
  "Apparel",
  "Automotive Parts",
  "Books",
  "Chemicals",
  "Clothing",
  "Consumer Electronics",
  "Cosmetics",
  "Dry Goods",
  "Electronics",
  "Food",
  "Furniture",
  "Hardware",
  "Health & Wellness",
  "Household Items",
  "Industrial Equipment",
  "Jewelry",
  "Machinery",
  "Medical Supplies",
  "Office Supplies",
  "Personal Care",
  "Pet Supplies",
  "Pharmaceuticals",
  "Sports Equipment",
  "Toys",
  "Tools",
  "Watches",
  "Wine & Spirits",
  "Arts & Crafts",
  "Bedding",
  "Beverages",
  "Building Materials",
  "Cleaning Supplies",
  "DIY Kits",
  "Garden Supplies",
  "Gift Items",
  "Groceries",
  "Household Appliances",
  "Luxury Goods",
  "Musical Instruments",
  "Party Supplies",
  "Seasonal Decorations",
  "Shoes",
  "Small Appliances",
  "Souvenirs",
  "Stationery",
  "Sunglasses",
  "Technology Accessories",
  "Textiles",
  "Vitamins & Supplements",
  "Workwear",
];
